load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "construct_test",
    srcs = ["construct.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "get_as_test",
    srcs = ["get_as.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "get_test",
    srcs = ["get.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "parser_test",
    srcs = ["parser_test.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "value_array_test",
    srcs = ["value_array.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "value_basic_test",
    srcs = ["value_basic.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "value_non_container_test",
    srcs = ["value_non_container.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)

cc_test(
    name = "value_object_test",
    srcs = ["value_object.cpp"],
    deps = [
        "//:json_spirit",
        "@boost//:test.a",
    ],
)
