load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "io",
    srcs = ["io.cpp"],
    visibility = ["//visibility:public"],
    deps = ["//ciere"],
)

cc_library(
    name = "value",
    srcs = ["value.cpp"],
    visibility = ["//visibility:public"],
    deps = ["//ciere"],
)
